[
  {
    name: "Chitato",
    img: "https://www.static-src.com/wcsstore/Indraprastha/images/catalog/full//113/MTA-17978558/chitato_chitato-keripik-kentang-sapi-panggang-120g_full01.jpg",
    category: "Makanan Ringan",
    buy_price: 15000,
    sell_price: 16000,
    warehouse: [
      { warehouseName: "Malang", stock: 9 },
      { warehouseName: "Surabaya", stock: 8 },
      { warehouseName: "Jakarta", stock: 10 },
      { warehouseName: "Bali", stock: 6 },
    ],
  },
  {
    name: "Fanta",
    img: "https://www.static-src.com/wcsstore/Indraprastha/images/catalog/full//94/MTA-26423347/fanta_fanta-str-pet-1500-ml_full01.jpg",
    category: "Minuman Bersoda",
    buy_price: 10000,
    sell_price: 11000,
    warehouse: [
      { warehouseName: "Malang", stock: 4 },
      { warehouseName: "Surabaya", stock: 5 },
      { warehouseName: "Jakarta", stock: 8 },
      { warehouseName: "Bali", stock: 5 },
    ],
  },
  {
    name: "M&M",
    img: "https://www.static-src.com/wcsstore/Indraprastha/images/catalog/full//96/MTA-26339442/no-brand_m-m-s-chocolate-candies-milk-200g_full01.jpg",
    category: "Permen",
    buy_price: 90000,
    sell_price: 100000,
    warehouse: [
      { warehouseName: "Malang", stock: 8 },
      { warehouseName: "Surabaya", stock: 2 },
      { warehouseName: "Jakarta", stock: 5 },
      { warehouseName: "Bali", stock: 7 },
    ],
  },
  {
    name: "Ketumbar Bubuk",
    img: "https://www.static-src.com/wcsstore/Indraprastha/images/catalog/full//84/MTA-3021508/koepoe-koepoe_koepoe-koepoe-ketumbar-bubuk-25-gr_full02.jpg",
    category: "Bumbu Masak",
    buy_price: 2000,
    sell_price: 3000,
    warehouse: [
      { warehouseName: "Malang", stock: 9 },
      { warehouseName: "Surabaya", stock: 8 },
      { warehouseName: "Jakarta", stock: 10 },
      { warehouseName: "Bali", stock: 6 },
    ],
  },
  {
    name: "Bango Kecap Manis ",
    img: "https://www.static-src.com/wcsstore/Indraprastha/images/catalog/full//111/MTA-16729878/bango_bango_kecap_manis_pouch_550ml_-_kecap_manis_refill-_soy_sauce-_kecap_manis_botol_full02_nbkzxy15.jpg",
    category: "Bumbu Dapur",
    buy_price: 24000,
    sell_price: 25000,
    warehouse: [
      { warehouseName: "Malang", stock: 9 },
      { warehouseName: "Surabaya", stock: 8 },
      { warehouseName: "Jakarta", stock: 10 },
      { warehouseName: "Bali", stock: 6 },
    ],
  },
  {
    name: "Gulaku",
    img: "https://www.static-src.com/wcsstore/Indraprastha/images/catalog/full//87/MTA-3719201/gulaku_semarang---gulaku-premium--1-kg-_full04.jpg",
    category: "Bumbu Dapur",
    buy_price: 15000,
    sell_price: 16000,
    warehouse: [
      { warehouseName: "Malang", stock: 9 },
      { warehouseName: "Surabaya", stock: 8 },
      { warehouseName: "Jakarta", stock: 10 },
      { warehouseName: "Bali", stock: 6 },
    ],
  },
  {
    name: "Oreo",
    img: "https://www.static-src.com/wcsstore/Indraprastha/images/catalog/full//87/MTA-3719201/gulaku_semarang---gulaku-premium--1-kg-_full04.jpg",
    category: "Makanan Ringan",
    buy_price: 8000,
    sell_price: 9000,
    warehouse: [
      { warehouseName: "Malang", stock: 9 },
      { warehouseName: "Surabaya", stock: 8 },
      { warehouseName: "Jakarta", stock: 10 },
      { warehouseName: "Bali", stock: 6 },
    ],
  },
  {
    name: "Pringles",
    img: "https://www.static-src.com/wcsstore/Indraprastha/images/catalog/full/UK-0041912/pringles_pringles_original_-107_g-_pe11007_full11_ngf9exi7.jpeg",
    category: "Makanan Ringan",
    buy_price: 2000,
    sell_price: 3000,
    warehouse: [
      { warehouseName: "Malang", stock: 9 },
      { warehouseName: "Surabaya", stock: 8 },
      { warehouseName: "Jakarta", stock: 10 },
      { warehouseName: "Bali", stock: 6 },
    ],
  },
  {
    name: "Ketumbar Bubuk",
    img: "https://www.static-src.com/wcsstore/Indraprastha/images/catalog/full//84/MTA-3021508/koepoe-koepoe_koepoe-koepoe-ketumbar-bubuk-25-gr_full02.jpg",
    category: "Bumbu Dapur",
    buy_price: 2000,
    sell_price: 3000,
    warehouse: [
      { warehouseName: "Malang", stock: 9 },
      { warehouseName: "Surabaya", stock: 8 },
      { warehouseName: "Jakarta", stock: 10 },
      { warehouseName: "Bali", stock: 6 },
    ],
  },
  {
    name: "Ketumbar Bubuk",
    img: "https://www.static-src.com/wcsstore/Indraprastha/images/catalog/full//84/MTA-3021508/koepoe-koepoe_koepoe-koepoe-ketumbar-bubuk-25-gr_full02.jpg",
    category: "Bumbu Dapur",
    buy_price: 2000,
    sell_price: 3000,
    warehouse: [
      { warehouseName: "Malang", stock: 9 },
      { warehouseName: "Surabaya", stock: 8 },
      { warehouseName: "Jakarta", stock: 10 },
      { warehouseName: "Bali", stock: 6 },
    ],
  },
  {
    name: "Ketumbar Bubuk",
    img: "https://www.static-src.com/wcsstore/Indraprastha/images/catalog/full//84/MTA-3021508/koepoe-koepoe_koepoe-koepoe-ketumbar-bubuk-25-gr_full02.jpg",
    category: "Bumbu Dapur",
    buy_price: 2000,
    sell_price: 3000,
    warehouse: [
      { warehouseName: "Malang", stock: 9 },
      { warehouseName: "Surabaya", stock: 8 },
      { warehouseName: "Jakarta", stock: 10 },
      { warehouseName: "Bali", stock: 6 },
    ],
  },
];
